export default {
	SET_HAS_SERIES_PASSES: 'TEC-TICKETS-FLEXIBLE-TICKETS/SET_HAS_SERIES_PASSES',
	SET_IS_IN_SERIES: 'TEC-TICKETS-FLEXIBLE-TICKETS/SET_IS_IN_SERIES',
	SET_DEFAULT_TICKET_DESCRIPTION:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_DEFAULT_TICKET_DESCRIPTION',
	SET_SERIES_PASS_TOTAL_CAPACITY:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_SERIES_PASS_TOTAL_CAPACITY',
	SET_SERIES_PASS_TOTAL_AVAILABLE:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_SERIES_PASS_TOTAL_AVAILABLE',
	SET_SERIES_INFORMATION:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_SERIES_INFORMATION',
	SET_MULTIPLE_PROVIDERS_NOTICE_TEMPLATE:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_MULTIPLE_PROVIDERS_NOTICE_TEMPLATE',
};
