export default {
	SET_DEFAULT_TICKET_DESCRIPTION:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_DEFAULT_TICKET_DESCRIPTION',
	SET_MULTIPLE_PROVIDERS_NOTICE_TEMPLATE:
		'TEC-TICKETS-FLEXIBLE-TICKETS/SET_MULTIPLE_PROVIDERS_NOTICE_TEMPLATE',
	SET_SERIES_DATA: 'TEC-TICKETS-FLEXIBLE-TICKETS/SET_SERIES_DATA',
};
