name: 'FT Codeception Tests'
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.php_check.outputs.php_files_changed }}
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repo
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          token: ${{ secrets.GH_BOT_TOKEN }}
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Check if any PHP files have changed
      # ------------------------------------------------------------------------------
      - name: Check for PHP file changes
        id: php_check
        uses: ./.github/actions/check-php-changes
      # ------------------------------------------------------------------------------
  test:
    needs: check
    if: needs.check.outputs.run_tests
    strategy:
      fail-fast: false
      matrix:
        suite:
          - ft_smoketest
          - ft_integration
          - ft_ct1_migration
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repo
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_BOT_TOKEN }}
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Checkout slic
      # ------------------------------------------------------------------------------
      - name: Checkout slic
        uses: actions/checkout@v4
        with:
          repository: stellarwp/slic
          ref: main
          path: slic
          fetch-depth: 1
      # ------------------------------------------------------------------------------
      # Prepare our composer cache directory
      # ------------------------------------------------------------------------------
      - name: Get Composer Cache Directory
        id: get-composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)-${{ secrets.COMPOSER_CACHE_KEY }}"
      - uses: actions/cache@v4
        id: composer-cache
        with:
          path: ${{ steps.get-composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ secrets.COMPOSER_CACHE_KEY }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      # ------------------------------------------------------------------------------
      # Initialize slic
      # ------------------------------------------------------------------------------
      - name: Set up slic env vars
        run: |
          echo "SLIC_BIN=${GITHUB_WORKSPACE}/slic/slic" >> $GITHUB_ENV
          echo "SLIC_WP_DIR=${GITHUB_WORKSPACE}/slic/_wordpress" >> $GITHUB_ENV
          echo "SLIC_WORDPRESS_DOCKERFILE=Dockerfile.base" >> $GITHUB_ENV
      - name: Set run context for slic
        run: echo "SLIC=1" >> $GITHUB_ENV && echo "CI=1" >> $GITHUB_ENV
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
      - name: Set up slic for CI
        run: |
          cd ${GITHUB_WORKSPACE}/..
          ${SLIC_BIN} here
          ${SLIC_BIN} interactive off
          ${SLIC_BIN} build-prompt off
          ${SLIC_BIN} build-subdir off
          ${SLIC_BIN} xdebug off
          ${SLIC_BIN} composer-cache set /home/runner/.cache/composer
          ${SLIC_BIN} debug on
          ${SLIC_BIN} info
          ${SLIC_BIN} config
      # ------------------------------------------------------------------------------
      # Start the Chrome container
      # ------------------------------------------------------------------------------
      - name: Start the Chrome container
        if: matrix.suite == 'acceptance'
        run: ${SLIC_BIN} up chrome
      # ------------------------------------------------------------------------------
      # Clone dependencies using smart checkout
      # ------------------------------------------------------------------------------
      - name: Clone TEC
        uses: ./.github/actions/smart-checkout
        with:
          other_repo: the-events-calendar/the-events-calendar
          path: the-events-calendar
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Init TEC
        run: |
          mv ${GITHUB_WORKSPACE}/the-events-calendar ${GITHUB_WORKSPACE}/../the-events-calendar
          ${SLIC_BIN} use the-events-calendar
          ${SLIC_BIN} composer install --no-dev
      - name: Set up TEC Common
        run: |
          ${SLIC_BIN} use the-events-calendar/common
          ${SLIC_BIN} composer install --no-dev
      - name: Clone ECP
        uses: ./.github/actions/smart-checkout
        with:
          other_repo: the-events-calendar/events-pro
          path: events-pro
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Init ECP
        run: |
          mv ${GITHUB_WORKSPACE}/events-pro ${GITHUB_WORKSPACE}/../events-pro
          ${SLIC_BIN} use events-pro
          ${SLIC_BIN} composer install --no-dev
      # ------------------------------------------------------------------------------
      # Set up ET Common
      # ------------------------------------------------------------------------------
      - name: Set up ET Common
        run: |
          ${SLIC_BIN} use event-tickets/common
          ${SLIC_BIN} composer install --no-dev
      # ------------------------------------------------------------------------------
      # Set up ET Common (npm install and build)
      # ------------------------------------------------------------------------------
      - name: Set up ET Common (npm)
        if: matrix.suite == 'acceptance'
        run: |
          ${SLIC_BIN} npm install
          ${SLIC_BIN} npm run build
      # ------------------------------------------------------------------------------
      # Set up ET
      # ------------------------------------------------------------------------------
      - name: Set up ET
        run: |
          ${SLIC_BIN} use event-tickets
          ${SLIC_BIN} composer install
      # ------------------------------------------------------------------------------
      # Set up ET (npm install and build)
      # ------------------------------------------------------------------------------
      - name: Set up ET (npm)
        if: matrix.suite == 'acceptance'
        run: |
          ${SLIC_BIN} npm install
          ${SLIC_BIN} npm run build
      # ------------------------------------------------------------------------------
      # Init WordPress container
      # ------------------------------------------------------------------------------
      - name: Init the WordPress container
        run: |
          ${SLIC_BIN} up wordpress
          ${SLIC_BIN} wp core version
          ${SLIC_BIN} wp core update --force --version=6.6
          ${SLIC_BIN} wp core version
      # ------------------------------------------------------------------------------
      # Install and activate TwentyTwenty
      # ------------------------------------------------------------------------------
      - name: Install and activate TwentyTwenty
        run:  ${SLIC_BIN} wp theme install twentytwenty --activate
      # ------------------------------------------------------------------------------
      # Run tests
      # ------------------------------------------------------------------------------
      - name: Run suite tests
        run: ${SLIC_BIN} run ${{ matrix.suite }} --ext DotReporter
      # ------------------------------------------------------------------------------
      # Upload artifacts (On failure)
      # ------------------------------------------------------------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure
        with:
          name: output ${{ matrix.suite }}
          path: tests/_output/
          retention-days: 7
